site_name: FIT-Lab
site_url: https://olektronikk.github.io/md/

nav:
  - ToDo: OTHER/ToDo.md
  - Links: OTHER/usefule_links.md
  - Organizational matters: OTHER/Organizational_matters.md
 # - GBT: GBT/gbt.md
 # - IPBUS: IPBUS/ipbus.md
 # - Common: COMMON/common.md
  - Lab C2 413: LAB/lab.md
 # - CRU: CRU/cru.md
 # - PM: PM/pm.md
  # - Master Thesis: MASTER_THESIS/master_thesis.md
  # - FPGA Vivado: FPGA_PROJECTS/fpga_projects.md
  # - My: 
  #   - MY: MY/my.md
  #   - Altium: MY/altium.md
  #   - RX/TX: MY/rxtx.md
  




theme:
  name: material
  # logo: logo_7.jpg
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.details

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - md_in_html

  - attr_list
  - md_in_html
  - pymdownx.blocks.caption


  # ![Running disparity](IMG/RXTX/image_2.png){width=300 style="display: block; margin: auto;"
  # 🟢📄🌐